config:
    prefix: "&b[RALogin]"
    miniprefix: "&b»"
    tokensperday: 1
    currency: "dollars"
rewards:
    prize:
        price: 15
        money: 1000
        items: // - ItemID;Amount;Damage;DisplayName
        - 256;4;0;Slightly Shiny Shovel
        - 265;16;0;Iron Ingot
        - 152;1;0;Basic Energy Cube
        commands: // - Command;DisplayName
        - heal %PLAYER%;Full heal